name: Update Spotify Stats
on:
  workflow_dispatch:

jobs:
  update_spotify_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios fs
          
      - name: Update Spotify Playlist
        run: |
          node .github/workflows/fetch_spotify_data.js
          
      - name: Commit Readme
        run: |
          git add TEST.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update Spotify Stats" TEST.md

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
